name: Docker publish sing-box

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Image version"
        required: false

permissions:
  contents: read
  packages: write

env:
  REGISTRY: ghcr.io
  IMAGE_OWNER: ${{ github.repository_owner }}
  IMAGE_NAME: sing-box

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if version is missing on main
        if: github.ref_name == 'main'
        run: |
          if [ -z "${{ github.event.inputs.version }}" ]; then
            echo "âŒ You must provide 'version' when running workflow on main branch."
            exit 1
          fi

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
        with:
          platforms: |
            - linux/amd64
            - linux/arm64

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into registry ${{ env.REGISTRY }}
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set environment based on branch
        id: env
        run: |
          if [ "${GITHUB_REF_NAME}" = "main" ]; then
            echo "environment=main" >> $GITHUB_OUTPUT
          else
            echo "environment=dev" >> $GITHUB_OUTPUT
          fi

      - name: Define image tags
        id: tags
        run: |
          if [ "${{ steps.env.outputs.environment }}" = "main" ]; then
            if [ -n "${{ github.event.inputs.version }}" ]; then
              echo "tags<<EOF" >> $GITHUB_OUTPUT
              echo "${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:latest" >> $GITHUB_OUTPUT
              echo "${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:${{ github.event.inputs.version }}" >> $GITHUB_OUTPUT
              echo "EOF" >> $GITHUB_OUTPUT
            else
              echo "tags=${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:latest" >> $GITHUB_OUTPUT
            fi
          else
            echo "tags=${{ env.REGISTRY }}/${{ env.IMAGE_OWNER }}/${{ env.IMAGE_NAME }}:dev" >> $GITHUB_OUTPUT
          fi

      - name: Build and push sing-box image
        uses: docker/build-push-action@v6
        with:
          context: ./
          push: true
          provenance: false
          platforms: linux/amd64,linux/arm64
          tags: ${{ steps.tags.outputs.tags }}
