name: Vulnerability Scan sing-box
permissions:
  contents: read
  pull-requests: write

on:
  schedule:
    - cron: '30 1 */7 * *'
  workflow_dispatch: ~

jobs:
  vulnerability-scan:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v4

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_LOGIN }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Pull Docker Image from GitHub Packages
      run: |
        docker pull ghcr.io/jinndi/sing-box:latest

    - name: Analyze for critical and high CVEs
      uses: docker/scout-action@v1
      id: docker-scout-cves
      with:
        command: cves,recommendations
        image: ghcr.io/jinndi/sing-box:latest
        sarif-file: sarif.output.json
        summary: true

    - name: Upload Scan Report as Artifact
      uses: actions/upload-artifact@v4
      with:
        name: vulnerability-scan-report
        path: sarif.output.json
